# ----------- CONFIGURABLE START -----------
title:            "Louis|GitHub blog"
description:      "机器学习应用研究。"
url:              https://7568.github.io # 域名
signoff:          "Louis" # Your name
#facebook_appid:   #liberxue
google_analytics: level-choir-331113
share:            true 
# 分页
paginate: 16
paginate_path: "louispage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         图像处理
    url:          images-process
    external:     false
  - name:         文本处理
    url:          /text-process
    external:     false
  - name:         time series 处理
    url:          /time-series-process
    external:     false
  - name:         其他杂记
    url:          /others
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
